matrix:
  include:
  - os: osx
    osx_image: xcode12
    language: cpp
    addons:
      homebrew:
        packages:
          - gtkmm3
          - zlib
          - openssl
          - nlohmann-json
          - sqlite

script:
  - |
    git submodule init
    git submodule update
    mkdir build
    cd build
    cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_PKGCONFIG=ON -DDISABLE_MBEDTLS=ON ../
    make

before_deploy:
  - |
    mkdir out
    cp abaddon out/abaddon

deploy:
  provider: s3
  local_dir: out
  upload-dir: travis-$TRAVIS_BRANCH
  skip_cleanup: true
  bucket: "pogger-space"
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_KEY
  endpoint: "https://nyc3.digitaloceanspaces.com"
  region: nyc3
  acl: public_read
  overwrite: true
  on:
    all_branches: true
